version: "3"
services:
  dispatcher:
    image: koduki/sqljudge
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./:/app
  problem0001:
    image: koduki/sqljudge-0001
    ports:
      - "80:80"